const countries = [
    {"id": 1,"value":"AF", "label":"Afghanistan"},
    {"id": 2,"value":"AX", "label":"Åland Islands"},
    {"id": 3,"value":"AL", "label":"Albania"},
    {"id": 4,"value":"DZ", "label":"Algeria"},
    {"id": 5,"value":"AS", "label":"American Samoa"},
    {"id": 6,"value":"AD", "label":"Andorra"},
    {"id": 7,"value":"AO", "label":"Angola"},
    {"id": 8,"value":"AI", "label":"Anguilla"},
    {"id": 9,"value":"AQ", "label":"Antarctica"},
    {"id": 10,"value":"AG", "label":"Antigua and Barbuda"},
    {"id": 11,"value":"AR", "label":"Argentina"},
    {"id": 12,"value":"AM", "label":"Armenia"},
    {"id": 13,"value":"AW", "label":"Aruba"},
    {"id": 14,"value":"AU", "label":"Australia"},
    {"id": 15,"value":"AT", "label":"Austria"},
    {"id": 16,"value":"AZ", "label":"Azerbaijan"},
    {"id": 17,"value":"BS", "label":"Bahamas"},
    {"id": 18,"value":"BH", "label":"Bahrain"},
    {"id": 19,"value":"BD", "label":"Bangladesh"},
    {"id": 20,"value":"BB", "label":"Barbados"},
    {"id": 21,"value":"BY", "label":"Belarus"},
    {"id": 22,"value":"BE", "label":"Belgium"},
    {"id": 23,"value":"BZ", "label":"Belize"},
    {"id": 24,"value":"BJ", "label":"Benin"},
    {"id": 25,"value":"BM", "label":"Bermuda"},
    {"id": 26,"value":"BT", "label":"Bhutan"},
    {"id": 27,"value":"BO", "label":"Bolivia"},
    {"id": 28,"value":"BA", "label":"Bosnia and Herzegovina"},
    {"id": 29,"value":"BW", "label":"Botswana"},
    {"id": 30,"value":"BV", "label":"Bouvet Island"},
    {"id": 31,"value":"BR", "label":"Brazil"},
    {"id": 32,"value":"IO", "label":"British Indian Ocean Territory"},
    {"id": 33,"value":"BN", "label":"Brunei Darussalam"},
    {"id": 34,"value":"BG", "label":"Bulgaria"},
    {"id": 35,"value":"BF", "label":"Burkina Faso"},
    {"id": 36,"value":"BI", "label":"Burundi"},
    {"id": 37,"value":"KH", "label":"Cambodia"},
    {"id": 38,"value":"CM", "label":"Cameroon"},
    {"id": 39,"value":"CA", "label":"Canada"},
    {"id": 40,"value":"CV", "label":"Cape Verde"},
    {"id": 41,"value":"KY", "label":"Cayman Islands"},
    {"id": 42,"value":"CF", "label":"Central African Republic"},
    {"id": 43,"value":"TD", "label":"Chad"},
    {"id": 44,"value":"CL", "label":"Chile"},
    {"id": 45,"value":"CN", "label":"China"},
    {"id": 46,"value":"CX", "label":"Christmas Island"},
    {"id": 47,"value":"CC", "label":"Cocos (Keeling) Islands"},
    {"id": 48,"value":"CO", "label":"Colombia"},
    {"id": 49,"value":"KM", "label":"Comoros"},
    {"id": 50,"value":"CG", "label":"Congo"},
    {"id": 51,"value":"CD", "label":"Congo, The Democratic Republic of the"},
    {"id": 52,"value":"CK", "label":"Cook Islands"},
    {"id": 53,"value":"CR", "label":"Costa Rica"},
    {"id": 54,"value":"CI", "label":"Cote D'Ivoire"},
    {"id": 55,"value":"HR", "label":"Croatia"},
    {"id": 56,"value":"CU", "label":"Cuba"},
    {"id": 57,"value":"CY", "label":"Cyprus"},
    {"id": 58,"value":"CZ", "label":"Czech Republic"},
    {"id": 59,"value":"DK", "label":"Denmark"},
    {"id": 60,"value":"DJ", "label":"Djibouti"},
    {"id": 61,"value":"DM", "label":"Dominica"},
    {"id": 62,"value":"DO", "label":"Dominican Republic"},
    {"id": 63,"value":"EC", "label":"Ecuador"},
    {"id": 64,"value":"EG", "label":"Egypt"},
    {"id": 65,"value":"SV", "label":"El Salvador"},
    {"id": 66,"value":"GQ", "label":"Equatorial Guinea"},
    {"id": 67,"value":"ER", "label":"Eritrea"},
    {"id": 68,"value":"EE", "label":"Estonia"},
    {"id": 69,"value":"ET", "label":"Ethiopia"},
    {"id": 70,"value":"FK", "label":"Falkland Islands (Malvinas)"},
    {"id": 71,"value":"FO", "label":"Faroe Islands"},
    {"id": 72,"value":"FJ", "label":"Fiji"},
    {"id": 73,"value":"FI", "label":"Finland"},
    {"id": 74,"value":"FR", "label":"France"},
    {"id": 75,"value":"GF", "label":"French Guiana"},
    {"id": 76,"value":"PF", "label":"French Polynesia"},
    {"id": 77,"value":"TF", "label":"French Southern Territories"},
    {"id": 78,"value":"GA", "label":"Gabon"},
    {"id": 79,"value":"GM", "label":"Gambia"},
    {"id": 80,"value":"GE", "label":"Georgia"},
    {"id": 81,"value":"DE", "label":"Germany"},
    {"id": 82,"value":"GH", "label":"Ghana"},
    {"id": 83,"value":"GI", "label":"Gibraltar"},
    {"id": 84,"value":"GR", "label":"Greece"},
    {"id": 85,"value":"GL", "label":"Greenland"},
    {"id": 86,"value":"GD", "label":"Grenada"},
    {"id": 87,"value":"GP", "label":"Guadeloupe"},
    {"id": 88,"value":"GU", "label":"Guam"},
    {"id": 89,"value":"GT", "label":"Guatemala"},
    {"id": 90,"value":"GG", "label":"Guernsey"},
    {"id": 91,"value":"GN", "label":"Guinea"},
    {"id": 92,"value":"GW", "label":"Guinea-Bissau"},
    {"id": 93,"value":"GY", "label":"Guyana"},
    {"id": 94,"value":"HT", "label":"Haiti"},
    {"id": 95,"value":"HM", "label":"Heard Island and Mcdonald Islands"},
    {"id": 96,"value":"VA", "label":"Holy See (Vatican City State)"},
    {"id": 97,"value":"HN", "label":"Honduras"},
    {"id": 98,"value":"HK", "label":"Hong Kong"},
    {"id": 99,"value":"HU", "label":"Hungary"},
    {"id": 100,"value":"IS", "label":"Iceland"},
    {"id": 101,"value":"IN", "label":"India"},
    {"id": 102,"value":"ID", "label":"Indonesia"},
    {"id": 103,"value":"IR", "label":"Iran, Islamic Republic Of"},
    {"id": 104,"value":"IQ", "label":"Iraq"},
    {"id": 105,"value":"IE", "label":"Ireland"},
    {"id": 106,"value":"IM", "label":"Isle of Man"},
    {"id": 107,"value":"IL", "label":"Israel"},
    {"id": 108,"value":"IT", "label":"Italy"},
    {"id": 109,"value":"JM", "label":"Jamaica"},
    {"id": 110,"value":"JP", "label":"Japan"},
    {"id": 111,"value":"JE", "label":"Jersey"},
    {"id": 112,"value":"JO", "label":"Jordan"},
    {"id": 113,"value":"KZ", "label":"Kazakhstan"},
    {"id": 114,"value":"KE", "label":"Kenya"},
    {"id": 115,"value":"KI", "label":"Kiribati"},
    {"id": 116,"value":"KP", "label":"Korea, Democratic People's Republic of"},
    {"id": 117,"value":"KR", "label":"Korea, Republic of"},
    {"id": 118,"value":"KW", "label":"Kuwait"},
    {"id": 119,"value":"KG", "label":"Kyrgyzstan"},
    {"id": 120,"value":"LA", "label":"Lao People's Democratic Republic"},
    {"id": 121,"value":"LV", "label":"Latvia"},
    {"id": 122,"value":"LB", "label":"Lebanon"},
    {"id": 123,"value":"LS", "label":"Lesotho"},
    {"id": 124,"value":"LR", "label":"Liberia"},
    {"id": 125,"value":"LY", "label":"Libyan Arab Jamahiriya"},
    {"id": 126,"value":"LI", "label":"Liechtenstein"},
    {"id": 127,"value":"LT", "label":"Lithuania"},
    {"id": 128,"value":"LU", "label":"Luxembourg"},
    {"id": 129,"value":"MO", "label":"Macao"},
    {"id": 130,"value":"MK", "label":"Macedonia, The Former Yugoslav Republic of"},
    {"id": 131,"value":"MG", "label":"Madagascar"},
    {"id": 132,"value":"MW", "label":"Malawi"},
    {"id": 133,"value":"MY", "label":"Malaysia"},
    {"id": 134,"value":"MV", "label":"Maldives"},
    {"id": 134,"value":"ML", "label":"Mali"},
    {"id": 135,"value":"MT", "label":"Malta"},
    {"id": 136,"value":"MH", "label":"Marshall Islands"},
    {"id": 137,"value":"MQ", "label":"Martinique"},
    {"id": 138,"value":"MR", "label":"Mauritania"},
    {"id": 139,"value":"MU", "label":"Mauritius"},
    {"id": 140,"value":"YT", "label":"Mayotte"},
    {"id": 141,"value":"MX", "label":"Mexico"},
    {"id": 142,"value":"FM", "label":"Micronesia, Federated States of"},
    {"id": 143,"value":"MD", "label":"Moldova, Republic of"},
    {"id": 144,"value":"MC", "label":"Monaco"},
    {"id": 145,"value":"MN", "label":"Mongolia"},
    {"id": 146,"value":"MS", "label":"Montserrat"},
    {"id": 147,"value":"MA", "label":"Morocco"},
    {"id": 148,"value":"MZ", "label":"Mozambique"},
    {"id": 149,"value":"MM", "label":"Myanmar"},
    {"id": 150,"value":"NA", "label":"Namibia"},
    {"id": 151,"value":"NR", "label":"Nauru"},
    {"id": 152,"value":"NP", "label":"Nepal"},
    {"id": 153,"value":"NL", "label":"Netherlands"},
    {"id": 154,"value":"AN", "label":"Netherlands Antilles"},
    {"id": 155,"value":"NC", "label":"New Caledonia"},
    {"id": 156,"value":"NZ", "label":"New Zealand"},
    {"id": 157,"value":"NI", "label":"Nicaragua"},
    {"id": 158,"value":"NE", "label":"Niger"},
    {"id": 159,"value":"NG", "label":"Nigeria"},
    {"id": 160,"value":"NU", "label":"Niue"},
    {"id": 161,"value":"NF", "label":"Norfolk Island"},
    {"id": 162,"value":"MP", "label":"Northern Mariana Islands"},
    {"id": 163,"value":"NO", "label":"Norway"},
    {"id": 164,"value":"OM", "label":"Oman"},
    {"id": 165,"value":"PK", "label":"Pakistan"},
    {"id": 166,"value":"PW", "label":"Palau"},
    {"id": 167,"value":"PS", "label":"Palestinian Territory, Occupied"},
    {"id": 168,"value":"PA", "label":"Panama"},
    {"id": 169,"value":"PG", "label":"Papua New Guinea"},
    {"id": 170,"value":"PY", "label":"Paraguay"},
    {"id": 171,"value":"PE", "label":"Peru"},
    {"id": 172,"value":"PH", "label":"Philippines"},
    {"id": 173,"value":"PN", "label":"Pitcairn"},
    {"id": 174,"value":"PL", "label":"Poland"},
    {"id": 175,"value":"PT", "label":"Portugal"},
    {"id": 176,"value":"PR", "label":"Puerto Rico"},
    {"id": 177,"value":"QA", "label":"Qatar"},
    {"id": 178,"value":"RE", "label":"Reunion"},
    {"id": 179,"value":"RO", "label":"Romania"},
    {"id": 180,"value":"RU", "label":"Russian Federation"},
    {"id": 181,"value":"RW", "label":"Rwanda"},
    {"id": 182,"value":"SH", "label":"Saint Helena"},
    {"id": 183,"value":"KN", "label":"Saint Kitts and Nevis"},
    {"id": 184,"value":"LC", "label":"Saint Lucia"},
    {"id": 185,"value":"PM", "label":"Saint Pierre and Miquelon"},
    {"id": 186,"value":"VC", "label":"Saint Vincent and the Grenadines"},
    {"id": 187,"value":"WS", "label":"Samoa"},
    {"id": 188,"value":"SM", "label":"San Marino"},
    {"id": 189,"value":"ST", "label":"Sao Tome and Principe"},
    {"id": 190,"value":"SA", "label":"Saudi Arabia"},
    {"id": 191,"value":"SN", "label":"Senegal"},
    {"id": 192,"value":"CS", "label":"Serbia and Montenegro"},
    {"id": 193,"value":"SC", "label":"Seychelles"},
    {"id": 194,"value":"SL", "label":"Sierra Leone"},
    {"id": 195,"value":"SG", "label":"Singapore"},
    {"id": 196,"value":"SK", "label":"Slovakia"},
    {"id": 197,"value":"SI", "label":"Slovenia"},
    {"id": 198,"value":"SB", "label":"Solomon Islands"},
    {"id": 199,"value":"SO", "label":"Somalia"},
    {"id": 200,"value":"ZA", "label":"South Africa"},
    {"id": 201,"value":"GS", "label":"South Georgia and the South Sandwich Islands"},
    {"id": 202,"value":"ES", "label":"Spain"},
    {"id": 203,"value":"LK", "label":"Sri Lanka"},
    {"id": 204,"value":"SD", "label":"Sudan"},
    {"id": 205,"value":"SR", "label":"Surilabel"},
    {"id": 206,"value":"SJ", "label":"Svalbard and Jan Mayen"},
    {"id": 207,"value":"SZ", "label":"Swaziland"},
    {"id": 208,"value":"SE", "label":"Sweden"},
    {"id": 209,"value":"CH", "label":"Switzerland"},
    {"id": 210,"value":"SY", "label":"Syrian Arab Republic"},
    {"id": 211,"value":"TW", "label":"Taiwan"},
    {"id": 212,"value":"TJ", "label":"Tajikistan"},
    {"id": 213,"value":"TZ", "label":"Tanzania, United Republic of"},
    {"id": 214,"value":"TH", "label":"Thailand"},
    {"id": 215,"value":"TL", "label":"Timor-Leste"},
    {"id": 216,"value":"TG", "label":"Togo"},
    {"id": 217,"value":"TK", "label":"Tokelau"},
    {"id": 218,"value":"TO", "label":"Tonga"},
    {"id": 219,"value":"TT", "label":"Trinidad and Tobago"},
    {"id": 220,"value":"TN", "label":"Tunisia"},
    {"id": 221,"value":"TR", "label":"Turkey"},
    {"id": 222,"value":"TM", "label":"Turkmenistan"},
    {"id": 223,"value":"TC", "label":"Turks and Caicos Islands"},
    {"id": 224,"value":"TV", "label":"Tuvalu"},
    {"id": 225,"value":"UG", "label":"Uganda"},
    {"id": 226,"value":"UA", "label":"Ukraine"},
    {"id": 227,"value":"AE", "label":"United Arab Emirates"},
    {"id": 228,"value":"GB", "label":"United Kingdom"},
    {"id": 229,"value":"US", "label":"United States"},
    {"id": 230,"value":"UM", "label":"United States Minor Outlying Islands"},
    {"id": 231,"value":"UY", "label":"Uruguay"},
    {"id": 232,"value":"UZ", "label":"Uzbekistan"},
    {"id": 233,"value":"VU", "label":"Vanuatu"},
    {"id": 234,"value":"VE", "label":"Venezuela"},
    {"id": 235,"value":"VN", "label":"Vietnam"},
    {"id": 236,"value":"VG", "label":"Virgin Islands, British"},
    {"id": 237,"value":"VI", "label":"Virgin Islands, U.S."},
    {"id": 238,"value":"WF", "label":"Wallis and Futuna"},
    {"id": 239,"value":"EH", "label":"Western Sahara"},
    {"id": 240,"value":"YE", "label":"Yemen"},
    {"id": 241,"value":"ZM", "label":"Zambia"},
    {"id": 252,"value":"ZW", "label":"Zimbabwe"}
];

export default countries;
